In [1]:
import pandas
csvFile = pandas.read_csv('original_names.csv')
csvFile

      Unnamed: 0 First Name  Last Name
0              0   Margreet   Nelemans
1              1       Tong       Zhao
2              2     Mattia      Molon
3              3       Nick        Bos
4              4      Zheng       Chen
...          ...        ...        ...
2342        2342     Jasper       Meer
2343        2343      Aukje       Boef
2344        2344       Jodi  Grooteman
2345        2345       Emma       Beek
2346        2346    Gregory      Aerts

[2347 rows x 3 columns]

In [7]:
import pandas as pd


# Get 10 random rows from the DataFrame
random_sample = csvFile.sample(n=10, random_state=2)

# Save the random sample to a new CSV file without index
output_path = "names.csv"
random_sample.to_csv(output_path, index=False)

random_sample

      Unnamed: 0 First Name       Last Name
1355        1355    Ibrahim        Garmouhi
571          571     Michel          Wijker
2331        2331      Nanne        Wielinga
2303        2303   Tingyuan           Zhang
1551        1551      Robin        Persoons
1405        1405       Guus      Westendorp
1205        1205     Aadesh            Shah
1687        1687       Koen          Klaren
1011        1011    Sangavi     Vijayakumar
1606        1606      Suman  Mahendra Kumar

In [8]:
random_sample

      Unnamed: 0 First Name       Last Name
1355        1355    Ibrahim        Garmouhi
571          571     Michel          Wijker
2331        2331      Nanne        Wielinga
2303        2303   Tingyuan           Zhang
1551        1551      Robin        Persoons
1405        1405       Guus      Westendorp
1205        1205     Aadesh            Shah
1687        1687       Koen          Klaren
1011        1011    Sangavi     Vijayakumar
1606        1606      Suman  Mahendra Kumar